### PR TITLE
Fix Initialize-ModuleBuild errors

### LINKED ISSUE #1: Version > 0.1.2 error on initialize
Hi,
on `Initialize-ModuleBuild`, after all user inputs are inserted, the script throw the error: `plaster/ModuleBuild/scaffold/build/docs/readthedocs not exists`.
On version <=  0.1.2 the error not occours.

### PR DESCRIPTION
**Pull request by ghost**
This PR fix #1 and #2 .

About issue 2, the errors is fired if **spaces** are present in the path of the project root directory. Now script path is enclosed in ''.

### CODE REVIEW

**Review by zloeber — APPROVED** [review]

**Comment by zloeber** [comment]
Great catch, I wasn't testing new projects in folders with spaces. Thanks much for fixing!

**Comment by ghost** [comment]
Hi @zloeber,
can you deploy this patched version into the PS Gallery?
I have not built the module.

Thanks.

**Comment by zloeber** [comment]
Sure, that's a fair enough request. I'll push it up shortly.

**Comment by ghost** [comment]
Thanks!

**Pull request merged**
