### PR TITLE
0.3.0 release

### PR DESCRIPTION
**Pull request by justin-p**
- Fixed issue with NLog by updating PlaterContent.ps1
- Fixed issue with Make.ps1 By adding --tags --always
- Fixed issue with Make.ps1. Write-Description -level 3 should be used instead of Write-Output
- Fixed issue with Get-SpecialPaths function by adding LoadBuildTools on InstallAndTestModule
- Fixed issue with -SourceModule parameter on Initialize-MBModuleBuild
- Fixed issue with the -AddCBH when there are no Params.
- Fixed issue with URLS in README.md. It was missing links to VSCode and the PS Extension.
- Fixed issue with the link to ChangeLog. ChangeLog in index.md was plural.
- Fixed issue that where caused when you where not using PlatyPS 0.12.0.
- Fixed issue with syntax highlight that was caused by the CommentBasedHelp function.
- Update ModuleBuild to adhere to the PSGallery ScriptAnalyzer ruleset.
- ModuleBuild now uses a standalone PSScriptAnalyzerSettings.psd1
- Updated ModuleBuild/.vscode/settings.json to include default indent size, set indent to space and use the project specific PSScriptAnalyzerSettings.psd1 file.
- Build reports are now saved on the following path `build\reports\$ModuleVersion\`.
- Included functions that are used during the build process are moved to its own repository.
- ModuleBuild now uses PSDepend to manage Build dependencies.
- ModuleBuild now uses PSDepend to manage Plugins.
- Revamped included tests.
- Make.ps1 is no longer dotsourced but included in `MakePlasterManifest.ps1`
- Updated the build scripts to better support CI/CD.
- The included version of Plaster is moved to the Plugin folder.
- Added a AppVeyor.yml template to the scaffold.
- Added a AppVeyor.yml to ModuleBuild itself.
- All functions are renamed to avoid conflicts with other modules.
- Cleaned up repo. Deleted unused code. Renamed/Moved existing files.
- Updated documentation to reflect above changes.

Before merging I think it's best to rename and move [ModuleBuildToolsTemp](https://github.com/justin-p/ModuleBuildToolsTemp) to a new repo under your account. If not I'd still like to rename it to ModuleBuildTools. Please let me know what you prefer so we can make the appropriated changes before merging.

### CODE REVIEW

**Comment by zloeber** [comment]
@justin-p - Wow, just wow

**Comment by justin-p** [comment]
Thanks for the quick merge!
Though I think you missed some notes I made at the bottom of the PR. 

As you might have seen by now I moved functions related to building to a standalone repo so they can be version tagged outside of ModuleBuild itself and be managed with PSDepend.

This is currently hosted under my name on Github and the PSGallery. This was intended as a temporary/placeholder solution while working on this PR, I called ModuleBuildTools*temp* for a reason :) It should really be renamed since this is kinda ugly.
 
For release 0.3.0 I think the ModuleBuildTools repo should be moved to your account if the main ModuleBuild branch is hosted there or they should be both moved to a Github organization.

It should be fairly easy to rename and move ModuleBuildTools over to another namespace. Once renamed and moved I would also appreciate if you could push a new release on the PSGallery. It's just easier to install and maintain that way. 

Lemme know what your thoughts are on this.

**Comment by zloeber** [comment]
I'm not going to lie, I've been hands off on all of my PowerShell code for over 2 years now (been diving deep into Python, Bash, Terraform, and all thinks Kubernetes among other things). ModuleBuild was one of my last projects before I took this PowerShell leave of absence. I released so much code and got so little feedback or contributions across several dozen projects that I didn't think anyone cared or that they amounted to anything other than my own learning experience.

So, on that note, your large PR made my day. It's awesome to know someone is willing to dive headfirst into something I put so much of my own free time into for others to use. So thanks for that first.

Would you be interested in maintaining this project? At this point you are more familiar with the code base than I am and you have sound ideas for furthering its usefulness to the community. I would only be a hindrance if I were needlessly gate-keeping something that was always meant to be a gift to the community anyway.

Thoughts?

**Comment by justin-p** [comment]
Yeah I would love to maintain it. Just accepted the invite.

**Pull request merged**
